version: "3.9"
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - 5432:5432